from os import getenv
DEBUG = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = getenv('SQLALCHEMY_DATABASE_URI')
UPLOAD_FOLDER = './pictures'
MAX_CONTENT_LENGTH = 8 * 1024 * 1024  # 8 mb
