"""Minor edits in products

Revision ID: 11a1be52a73b
Revises: ea0e57ea76cc
Create Date: 2022-04-05 07:14:24.253445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a1be52a73b'
down_revision = 'ea0e57ea76cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sales',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'sales',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
