"""Remove access key

Revision ID: 1a650002307a
Revises: f0542ec7cfff
Create Date: 2022-05-06 08:50:34.380035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a650002307a'
down_revision = 'f0542ec7cfff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
