"""Add products description and change in review

Revision ID: 808656c51039
Revises: f920d2a60943
Create Date: 2022-04-21 09:14:12.013970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808656c51039'
down_revision = 'f920d2a60943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('image_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'image_url')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
