"""Add sales and image_url fields

Revision ID: ea0e57ea76cc
Revises: 3582faa663e1
Create Date: 2022-04-05 07:09:08.720892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0e57ea76cc'
down_revision = '3582faa663e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sales', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('image_url', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'sales')
    # ### end Alembic commands ###
