"""Add relation users to orders

Revision ID: f0542ec7cfff
Revises: 4eaddbebd081
Create Date: 2022-05-03 17:35:45.411454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0542ec7cfff'
down_revision = '4eaddbebd081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_orders_owner_id_users'), 'orders', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_owner_id_users'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'owner_id')
    # ### end Alembic commands ###
